#pragma once
		   
enum class RENDER_GROUP
{
	CAMERA,
	PRIORITY,
	SHADOW,
	NONBLEND,
	SCREEN_EFFECT,
	BLEND,
	DECAL,
	BLOOM,
	NEON,
	NONLIGHT,
	OUTLINE,
	POSTPROCESS,
	UI,					// Deprecated
	UI_3D,
#ifdef _DEBUG
	DEBUG,
#endif
	MAX
};

enum class COMPONENT
{
	RENDERER,
	TRANSFORM,
	SHADER,
	TEXTURE,
	COLLIDER,
	MODEL,
	VIBUFFER,
	MESH,
	VIBUFFER_RECT,
	VIBUFFER_LINELIST,
	VIBUFFER_CUBE,
	VIBUFFER_SPHERE,
	VIBUFFER_INSTANCE_MESH,
	VIBUFFER_INSTANCE_MODEL,
	VIBUFFER_INSTANCE_POINT,
	VIBUFFER_INSTANCE_LINE,
	VIBUFFER_INSTANCE_RECT,
	PARTICLE_SYSTEM,
	KEYFRAME,
	MODEL_RENDERER,
	NAVIGATION,
	MAX
};

enum class BEHAVIOR
{
	CUSTOM,
	PHYSICS,
	ANIMATOR,
	CONTROL,
	MAX
};

enum class STATUS
{
	RUNNING,
	SUCCESS,
	FAILURE,
	MAX
};

enum class KEY_STATE	{ DOWN, HOLD, UP, NONE, MAX };
enum class LIGHTTYPE	{ DIRECTIONAL, POINT, SHADOW, MAX };
enum class SHADOWTYPE	{ DIRECTIONAL, DYNAMIC, PUBLIC, POINT, MAX };
enum class PIPELINE		{ WORLD, VIEW, PROJECTION, MAX };
enum class TRANSFORM	{ RIGHT, UP, LOOK, POSITION, MAX };
enum class MODEL		{ ANIM, NONANIM, MAX };
enum class COLLIDER		{ SPHERE, AABB, OBB, MAX };
enum class PICKER		{ LOCAL, WORLD, MAX };

enum class SHADER_STAGE { VS, HS, DS, GS, PS, CS, MAX };

enum class SCENE;
enum class COLLISION_GROUP;
enum class SOUND_CHANNEL;
enum class EFFECT;

enum class BONE
{
	REFERENCES = 4,
	SPINE = 54,
	SPINE1 = 55,
	EFF01 = 367,
	CAMERAPOS = 373,
	CAMERAPOS_END = 374
};

enum class CUTSCENE_CHANNEL
{
	CHANNEL_MAIN,
	CHANNEL_SUB_0,
	CHANNEL_SUB_1,
	CHANNEL_SUB_2,
	MAX,
};

enum class IMAGE_PROCESS
{
	PROCESS_TONEMAPPING,
	PROCESS_BLOOM,
	PROCESS_BLOOM_STRENGTH,
	PROCESS_LUT,
	PROCESS_NEON,
	MAX
};

enum class UI_LAYER
{
	LAYER_0,
	LAYER_1,
	LAYER_2,
	LAYER_3,
	LAYER_4,
	LAYER_5,
	LAYER_6,
	LAYER_7,
	CURSOR,
	MAX,
};

enum EVENTTYPE {
	TYPE_SOUND,
	TYPE_ANIMSPEED,
	CUSTOMFUNCTION1,
	CUSTOMFUNCTION2,
	CUSTOMFUNCTION3,
	CUSTOMFUNCTION4,
	CUSTOMFUNCTION5,
	CUSTOMFUNCTION6,
	CUSTOMFUNCTION7,
	CUSTOMFUNCTION8,
	CUSTOMFUNCTION9,
	CUSTOMFUNCTION10,
	CUSTOMFUNCTION11,
	CUSTOMFUNCTION12,
	CUSTOMFUNCTION13,
	CUSTOMFUNCTION14,
	CUSTOMFUNCTION15,
	CUSTOMFUNCTION16,
	CUSTOMFUNCTION17,
	CUSTOMFUNCTION18,
	CUSTOMFUNCTION19,
	CUSTOMFUNCTION20,
	CUSTOMFUNCTION21,
	CUSTOMFUNCTION22,
	CUSTOMFUNCTION23,
	CUSTOMFUNCTION24,
	CUSTOMFUNCTION25,
	CUSTOMFUNCTION26,
	CUSTOMFUNCTION27,
	CUSTOMFUNCTION28,
	CUSTOMFUNCTION29,
	CUSTOMFUNCTION30,
	CUSTOMFUNCTION31,
	CUSTOMFUNCTION32,

	TYPE_END
};

enum class NODE
{
	LEAF,
	DECORATOR,
	PARALLEL,
	SEQUENCE,
	SELECTOR,
	MAX
};

enum class ACTORTAG
{
	NONE,
	STATIC,
	INTERACTIVE,
	INTERACTIVE_BEAM,
	INTERACTIVE_SPECIAL,
	INTERACTIVE_BUS,
	FALLEN_OBJECT,
	MONSTER,
	PLAYER,
	PLAYER_ATTACK,
	PLAYER_BIGATTACK,
	PLAYER_KICK,
	MONSTER_ATTACK,
	MONSTER_BIGATTACK,
	MONSTER_BIGBODY,
	MONSTER_BIGBODY2,
	KAREN_BIGBODY,
	TEAMMATE,
	TEAMMATE_ATTACK,
	MONSTER_DODGESENCE,
	EVENT,
	FLY,
	ACTORTAG_END
};

enum class PLAYER_HURTTYPE { NONE, NORMAL, STRONG, AIR };

enum class INSTANCETYPE
{
	STATIC,
	DYNAMIC,
	MAX
};
